### ISSUE TITLE
Unable to start new project from scratch with Ember V1 addons errors

### ISSUE THREAD

**Issue by Polve** [prysmex/ember-eui#206]
I would like to give ember-eui another try (I'm not an experienced ember dev) so I created a new project this way:

`ember new --typescript --embroider --pnpm tmp
`

I then installed the missing peer dependencies this way:

`pnpm i -D ember-focus-trap moment
`

and finally installed ember-eui:

`ember install @ember-eui/core
`

if I try to start the project with

`pnpm start
`

I get this error:

```
Some V1 ember addons are resolving as incorrect peer dependencies. This makes it impossible for us to safely convert them to v2 format.

👇 👇 👇
👉 See https://github.com/embroider-build/embroider/blob/main/docs/peer-dependency-resolution-issues.md for an explanation of the problem and suggestions for fixing it.
👆 👆 👆

tmp@0.0.0 (dev)-> @ember-eui/core@8.0.44 -> ember-power-select@7.2.0 -> ember-basic-dropdown@7.3.0 -> ember-style-modifier@3.1.1
sees peerDep @ember/string@3.1.1
at /home/Work/sandbox/tmp/node_modules/.pnpm/@ember+string@3.1.1/node_modules/@ember/string
but @ember-eui/core@8.0.44 is using @ember/string@4.0.0
at /home/Work/sandbox/tmp/node_modules/.pnpm/@ember+string@4.0.0/node_modules/@ember/string

tmp@0.0.0 (dev)-> @ember-eui/core@8.0.44 -> ember-power-select@7.2.0 -> ember-basic-dropdown@7.3.0 -> ember-style-modifier@3.1.1
sees peerDep @ember/string@3.1.1
at /home/Work/sandbox/tmp/node_modules/.pnpm/@ember+string@3.1.1/node_modules/@ember/string
but tmp@0.0.0 is using @ember/string@4.0.0
at /home/Work/sandbox/tmp/node_modules/.pnpm/@ember+string@4.0.0/node_modules/@ember/string
```

**Comment by mkszepp** [comment]
yea... its an issue of this addon, which ships atm some outdated dependency packages. Your specific issue will be fixed by closing #205

I have also tested a little bit this addon today, because we have planned to use it in an ongoing project.
If you have a new clean app you need todo the following:
- downgrade `@ember/string` to `^3.1.1` 
- downgrade `@glimmer/components` to `^1.x`

in additional you need to remove this css import `import euiExtensions from "@ember-eui/core/styles/ember-eui.css"`, because its not exported.

If you use embroider (which if really recommended for new projects), you will run into additional 37 warnings while build...

```
WARNING in ../../.pnpm/@ember-eui+core@8.0.44_@babel+core@7.26.7_@ember+string@3.1.1_@glimmer+component@1.1.2_@babel_zp2r5i26gfc2u2s5y3zq5owbvi/node_modules/@ember-eui/core/dist/_app_/utils/transition.js 1:0-59
export 'default' (reexported as 'default') was not found in '@ember-eui/core/utils/transition' (possible exports: getDurationAndPerformOnFrame, getTransitionTimings, getWaitDuration, performOnFrame)
 @ ./assets/mp-client.js 393:13-53
```

**Comment by betocantu93** [comment]
Hey guys thanks for opening issues.

It's been some time since I try installing in a fresh app.

Currently we are actually using the branch v8-master at work because our main apps are stuck at 3.28. But don't worry: we are keeping master synced (feature/bug fixes wise).

That said, I'll make sure that master is up to date with fresh apps this weekend.

Thanks again,

And please feel free to PR or keep opening issues. We use this addon daily heavily--it's super alive.

**Comment by betocantu93** [comment]
Just to clarify:

Master branch deploys 10.x

v8-master 8.x

In theory, 10.x deploys are meant to be the ones working with fresh apps.

Can't recall exactly why 3.28 was not working with 10.x branch; I will have a look again--to see if v8 releases can be deprecated or not

**Comment by Polve** [comment]
Thanks for the great feedback, it's very nice to know the library is still very much alive!

I didn't notice there were two major releases (v9 and v10), why I can't find them on npm?

How may I use them?

**Comment by betocantu93** [comment]
Noticed master is on 11.x already

https://www.npmjs.com/package/@ember-eui/core/v/11.0.2

They are published. I will try to mark those as the main versions on npm.

And I will also update the readme 

8x is for legacy builds--as far as I can recall.

**Comment by Polve** [comment]
If you can update the project with current dependencies for @ember/string and @glimmer/components please notice that ember 6.2 has just been published so it would be nice to be compatible with latest release :-)

**Comment by Polve** [comment]
thank you @betocantu93 for the updated package! 

I still see a warning about @ember/string: the default installed is v4 while the required one is 3.1.1.

A quick search says that the package is being phased out so I took a quick look but I was unable to find/understand who is using it: is it possible to upgrade it or totally get rid of it?

**Comment by mkszepp** [comment]
ember/string v3 is a peerDependency of `ember-style-modifier` v3. The style modifier comes with ember basic dropdown and power select.

https://github.com/jelhan/ember-style-modifier/blob/41c47065815a0dee0012d21acd0e24776ea4db1d/package.json#L135

In `ember-style-modifier` v4 its supported also v4.

This means that basic dropdown / power select must be updated inside this addon to v8, than it is solved

**Comment by Polve** [comment]
I'm trying to follow the tutorial to verify I'm able to create a sample app: I noticed that the instructions at page https://ember-eui.vercel.app/docs/getting-started for v2 initializer have a couple of missing single ticks and they create syntax errors.

I suppose the line

>     service:eui-config'

should be

>     'service:eui-config'

while the line

>     euiButtonIcon.size': 's',

should be

>     'euiButtonIcon.size': 's',

Anyway, even after fixing if I try to start the app I get this error:

>  TypeError: appInstance.lookup is not a function

**Comment by betocantu93** [comment]
Yes, the docs are probably broken in those ticks.

Do you have a repo ? So I can see what you are trying?

I'm almost done with the updates to master branch. I think I just need to use a fork of ember-svg-jar.

Or find an alternative.

Because I think from 5.8 onwards ember-cli-babel must be 8.3+ and ember-cli-htmlbars like 6.3 or sep thing. What I'm trying to do is having the docs app to run on latest ember-source.

**Comment by Polve** [comment]
for now I'm not doing anything except trying to run an empty app using latest (current) version of everything

**Comment by betocantu93** [comment]
Im having trouble getting it to work, so many bumps.. with ember-source v6.

**Comment by betocantu93** [comment]
Ok so I manage to make it work with ember-source 6.2.0, please give it a try on version, all packages on version `12.0.0`.

Take a look to /site app if anything...

**Comment by betocantu93** [comment]
Although we are still missing ember-changeset-validations to release a newer version, in order to have @ember-eui/changeset-form working.
